"""Tests for package public API."""

import backend.app.services.consultation_brain as consultation_brain


def test_public_api_exports():
    expected = {
        "ConflictEngine",
        "ConflictEngineResult",
        "ConflictType",
        "ConsultationConflictResolution",
        "ALL_PRIORITY_DOMAINS",
        "ConsultationPriorityResult",
        "DomainPriority",
        "PriorityDomain",
        "PriorityEngine",
        "to_legacy_priorities",
        "RecommendationEngine",
        "RecommendationTier",
        "StructuredRecommendation",
        "ConsultationRecommendationResult",
        "RecommendationCategory",
        "ALL_RECOMMENDATION_CATEGORIES",
        "to_legacy_recommendations",
        "MasterConsultationEngine",
        "MasterConsultationLanguage",
        "MasterConsultationSection",
        "MasterConsultationSectionId",
        "NarrativeEngine",
        "NarrativeLanguage",
        "NarrativeSection",
        "NarrativeSectionId",
        "ConsultationBrain",
        "ConsultationBrainConfig",
        "ConsultationBrainOutput",
        "ConsultationConflict",
        "ConsultationEvidence",
        "ConsultationEvidenceBundle",
        "ConsultationInput",
        "ConsultationNarrative",
        "MasterConsultation",
        "ConsultationPriority",
        "ConsultationRecommendation",
        "EvidenceProvider",
        "AsyncEvidenceProvider",
        "Clock",
        "EvidenceCategory",
        "EvidenceSource",
        "ENGINE_VERSION",
        "PipelineStage",
        "UtcClock",
        "FixedClock",
        "EvidenceCollector",
        "EvidenceNormalizer",
        "consultation_brain_output_to_dict",
        "evidence_bundle_to_dict",
        "collect_evidence",
        "collect_evidence_async",
        "as_async_provider",
        "default_evidence_providers",
        "default_collection_providers",
        "YogaEvidenceProvider",
        "DashaEvidenceProvider",
        "TransitEvidenceProvider",
        "KPEvidenceProvider",
        "LalKitabEvidenceProvider",
        "RuleStudioEvidenceProvider",
        "CaseLearningEvidenceProvider",
        "FusionEvidenceProvider",
        "GoldenDatasetEvidenceProvider",
        "ProfessionalReportEvidenceProvider",
        "provider_sources",
    }
    assert expected.issubset(set(consultation_brain.__all__))
