"""initial_schema

Revision ID: fa7758df895a
Revises: 
Create Date: 2026-06-26 20:38:57.011221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa7758df895a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unspecified', name='gender', native_enum=False), server_default='unspecified', nullable=False),
    sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_clients_created_at', 'clients', ['created_at'], unique=False)
    op.create_index('ix_clients_email', 'clients', ['email'], unique=False)
    op.create_index('ix_clients_is_active', 'clients', ['is_active'], unique=False)
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=False)
    op.create_table('birth_details',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('person_name', sa.String(length=255), nullable=False),
    sa.Column('relationship_to_client', sa.Enum('self', 'spouse', 'child', 'parent', 'sibling', 'friend', 'other', name='relationship_type', native_enum=False), server_default='self', nullable=False),
    sa.Column('birth_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('birth_place_name', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'person_name', 'birth_datetime', name='uq_birth_details_client_person_datetime')
    )
    op.create_index('ix_birth_details_birth_datetime', 'birth_details', ['birth_datetime'], unique=False)
    op.create_index('ix_birth_details_client_id', 'birth_details', ['client_id'], unique=False)
    op.create_index('ix_birth_details_is_primary', 'birth_details', ['is_primary'], unique=False)
    op.create_table('generated_pdfs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('birth_detail_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('kundali', 'dasha', 'transit', 'lal_kitab', 'kp', 'remedy', 'combined', 'custom', name='pdf_report_type', native_enum=False), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), server_default='application/pdf', nullable=False),
    sa.Column('storage_backend', sa.Enum('local', 's3', 'gcs', name='pdf_storage_backend', native_enum=False), server_default='local', nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'generating', 'completed', 'failed', name='pdf_generation_status', native_enum=False), server_default='queued', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_pdfs_birth_detail_id', 'generated_pdfs', ['birth_detail_id'], unique=False)
    op.create_index('ix_generated_pdfs_client_id', 'generated_pdfs', ['client_id'], unique=False)
    op.create_index('ix_generated_pdfs_generated_at', 'generated_pdfs', ['generated_at'], unique=False)
    op.create_index('ix_generated_pdfs_report_type', 'generated_pdfs', ['report_type'], unique=False)
    op.create_index('ix_generated_pdfs_status', 'generated_pdfs', ['status'], unique=False)
    op.create_table('kp_reports',
    sa.Column('birth_detail_id', sa.UUID(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cuspal_chart', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('significators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ruling_planets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'archived', name='report_status', native_enum=False), server_default='completed', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kp_reports_birth_detail_id', 'kp_reports', ['birth_detail_id'], unique=False)
    op.create_index('ix_kp_reports_status', 'kp_reports', ['status'], unique=False)
    op.create_table('kundali_charts',
    sa.Column('birth_detail_id', sa.UUID(), nullable=False),
    sa.Column('chart_system', sa.Enum('vedic', 'western', name='chart_system', native_enum=False), server_default='vedic', nullable=False),
    sa.Column('ayanamsa', sa.Enum('lahiri', 'raman', 'kp', 'krishnamurti', 'yukteshwar', name='ayanamsa', native_enum=False), server_default='lahiri', nullable=False),
    sa.Column('house_system', sa.Enum('placidus', 'whole_sign', 'equal', 'sripathi', 'kp', name='house_system', native_enum=False), server_default='whole_sign', nullable=False),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('divisional_charts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computation_version', sa.String(length=32), server_default='1.0.0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'archived', name='report_status', native_enum=False), server_default='completed', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kundali_charts_birth_detail_id', 'kundali_charts', ['birth_detail_id'], unique=False)
    op.create_index('ix_kundali_charts_is_current', 'kundali_charts', ['is_current'], unique=False)
    op.create_index('ix_kundali_charts_status', 'kundali_charts', ['status'], unique=False)
    op.create_table('lal_kitab_reports',
    sa.Column('birth_detail_id', sa.UUID(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('house_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planetary_debts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_remedies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'archived', name='report_status', native_enum=False), server_default='completed', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lal_kitab_reports_birth_detail_id', 'lal_kitab_reports', ['birth_detail_id'], unique=False)
    op.create_index('ix_lal_kitab_reports_status', 'lal_kitab_reports', ['status'], unique=False)
    op.create_table('remedies',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('birth_detail_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('dasha', 'transit', 'lal_kitab', 'kp', 'kundali', 'ai', 'manual', name='remedy_source_type', native_enum=False), nullable=False),
    sa.Column('source_report_id', sa.UUID(), nullable=True),
    sa.Column('remedy_type', sa.Enum('mantra', 'gemstone', 'ritual', 'charity', 'fasting', 'yantra', 'color_therapy', 'lifestyle', 'other', name='remedy_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planet', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('prescribed', 'in_progress', 'completed', 'discontinued', name='remedy_status', native_enum=False), server_default='prescribed', nullable=False),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remedies_birth_detail_id', 'remedies', ['birth_detail_id'], unique=False)
    op.create_index('ix_remedies_client_id', 'remedies', ['client_id'], unique=False)
    op.create_index('ix_remedies_source', 'remedies', ['source_type', 'source_report_id'], unique=False)
    op.create_index('ix_remedies_status', 'remedies', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('birth_detail_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('unified_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interpretation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remedy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_birth_detail_id', 'reports', ['birth_detail_id'], unique=False)
    op.create_index('ix_reports_client_id', 'reports', ['client_id'], unique=False)
    op.create_index('ix_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_index('ix_reports_version', 'reports', ['version'], unique=False)
    op.create_table('transit_reports',
    sa.Column('birth_detail_id', sa.UUID(), nullable=False),
    sa.Column('reference_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('significant_transits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'archived', name='report_status', native_enum=False), server_default='completed', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transit_reports_birth_detail_id', 'transit_reports', ['birth_detail_id'], unique=False)
    op.create_index('ix_transit_reports_reference_datetime', 'transit_reports', ['reference_datetime'], unique=False)
    op.create_index('ix_transit_reports_status', 'transit_reports', ['status'], unique=False)
    op.create_table('user_queries',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('birth_detail_id', sa.UUID(), nullable=True),
    sa.Column('query_type', sa.Enum('general', 'kundali', 'dasha', 'transit', 'lal_kitab', 'kp', 'remedy', 'compatibility', name='query_type', native_enum=False), server_default='general', nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('received', 'processing', 'answered', 'failed', name='query_status', native_enum=False), server_default='received', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_queries_birth_detail_id', 'user_queries', ['birth_detail_id'], unique=False)
    op.create_index('ix_user_queries_client_id', 'user_queries', ['client_id'], unique=False)
    op.create_index('ix_user_queries_created_at', 'user_queries', ['created_at'], unique=False)
    op.create_index('ix_user_queries_query_type', 'user_queries', ['query_type'], unique=False)
    op.create_index('ix_user_queries_status', 'user_queries', ['status'], unique=False)
    op.create_table('dasha_reports',
    sa.Column('birth_detail_id', sa.UUID(), nullable=False),
    sa.Column('kundali_chart_id', sa.UUID(), nullable=True),
    sa.Column('dasha_system', sa.Enum('vimshottari', 'yogini', 'ashtottari', 'char', name='dasha_system', native_enum=False), server_default='vimshottari', nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_mahadasha', sa.String(length=32), nullable=True),
    sa.Column('current_antardasha', sa.String(length=32), nullable=True),
    sa.Column('current_pratyantardasha', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'archived', name='report_status', native_enum=False), server_default='completed', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_detail_id'], ['birth_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kundali_chart_id'], ['kundali_charts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dasha_reports_birth_detail_id', 'dasha_reports', ['birth_detail_id'], unique=False)
    op.create_index('ix_dasha_reports_generated_at', 'dasha_reports', ['generated_at'], unique=False)
    op.create_index('ix_dasha_reports_kundali_chart_id', 'dasha_reports', ['kundali_chart_id'], unique=False)
    op.create_index('ix_dasha_reports_status', 'dasha_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dasha_reports_status', table_name='dasha_reports')
    op.drop_index('ix_dasha_reports_kundali_chart_id', table_name='dasha_reports')
    op.drop_index('ix_dasha_reports_generated_at', table_name='dasha_reports')
    op.drop_index('ix_dasha_reports_birth_detail_id', table_name='dasha_reports')
    op.drop_table('dasha_reports')
    op.drop_index('ix_user_queries_status', table_name='user_queries')
    op.drop_index('ix_user_queries_query_type', table_name='user_queries')
    op.drop_index('ix_user_queries_created_at', table_name='user_queries')
    op.drop_index('ix_user_queries_client_id', table_name='user_queries')
    op.drop_index('ix_user_queries_birth_detail_id', table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_index('ix_transit_reports_status', table_name='transit_reports')
    op.drop_index('ix_transit_reports_reference_datetime', table_name='transit_reports')
    op.drop_index('ix_transit_reports_birth_detail_id', table_name='transit_reports')
    op.drop_table('transit_reports')
    op.drop_index('ix_reports_version', table_name='reports')
    op.drop_index('ix_reports_generated_at', table_name='reports')
    op.drop_index('ix_reports_client_id', table_name='reports')
    op.drop_index('ix_reports_birth_detail_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_remedies_status', table_name='remedies')
    op.drop_index('ix_remedies_source', table_name='remedies')
    op.drop_index('ix_remedies_client_id', table_name='remedies')
    op.drop_index('ix_remedies_birth_detail_id', table_name='remedies')
    op.drop_table('remedies')
    op.drop_index('ix_lal_kitab_reports_status', table_name='lal_kitab_reports')
    op.drop_index('ix_lal_kitab_reports_birth_detail_id', table_name='lal_kitab_reports')
    op.drop_table('lal_kitab_reports')
    op.drop_index('ix_kundali_charts_status', table_name='kundali_charts')
    op.drop_index('ix_kundali_charts_is_current', table_name='kundali_charts')
    op.drop_index('ix_kundali_charts_birth_detail_id', table_name='kundali_charts')
    op.drop_table('kundali_charts')
    op.drop_index('ix_kp_reports_status', table_name='kp_reports')
    op.drop_index('ix_kp_reports_birth_detail_id', table_name='kp_reports')
    op.drop_table('kp_reports')
    op.drop_index('ix_generated_pdfs_status', table_name='generated_pdfs')
    op.drop_index('ix_generated_pdfs_report_type', table_name='generated_pdfs')
    op.drop_index('ix_generated_pdfs_generated_at', table_name='generated_pdfs')
    op.drop_index('ix_generated_pdfs_client_id', table_name='generated_pdfs')
    op.drop_index('ix_generated_pdfs_birth_detail_id', table_name='generated_pdfs')
    op.drop_table('generated_pdfs')
    op.drop_index('ix_birth_details_is_primary', table_name='birth_details')
    op.drop_index('ix_birth_details_client_id', table_name='birth_details')
    op.drop_index('ix_birth_details_birth_datetime', table_name='birth_details')
    op.drop_table('birth_details')
    op.drop_index('ix_clients_phone', table_name='clients')
    op.drop_index('ix_clients_is_active', table_name='clients')
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_index('ix_clients_created_at', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
