"""Keyword and severity signal patterns for problem classification."""

from __future__ import annotations

from ai_engine.analyzers.problem.constants import ProblemCategory

CATEGORY_KEYWORDS: dict[ProblemCategory, tuple[str, ...]] = {
    ProblemCategory.MARRIAGE: (
        "marriage",
        "married",
        "spouse",
        "husband",
        "wife",
        "partner",
        "relationship",
        "divorce",
        "separation",
        "wedding",
        "engagement",
        "love",
        "compatibility",
        "delay in marriage",
        "marital",
    ),
    ProblemCategory.BUSINESS_FINANCE: (
        "business",
        "loss",
        "profit",
        "money",
        "finance",
        "financial",
        "debt",
        "loan",
        "bankruptcy",
        "investment",
        "trade",
        "shop",
        "company",
        "startup",
        "revenue",
        "cash",
        "wealth",
    ),
    ProblemCategory.CAREER: (
        "career",
        "job",
        "profession",
        "promotion",
        "employment",
        "workplace",
        "salary",
        "office",
        "profession",
        "interview",
        "unemployment",
        "boss",
    ),
    ProblemCategory.HEALTH: (
        "health",
        "illness",
        "disease",
        "sick",
        "medical",
        "hospital",
        "surgery",
        "chronic",
        "pain",
        "mental health",
        "depression",
        "anxiety",
    ),
    ProblemCategory.LEGAL: (
        "court",
        "case",
        "lawsuit",
        "litigation",
        "legal",
        "lawyer",
        "judge",
        "police",
        "arrest",
        "bail",
        "dispute",
        "fraud",
        "accused",
    ),
    ProblemCategory.EDUCATION: (
        "education",
        "study",
        "exam",
        "school",
        "college",
        "university",
        "degree",
        "learning",
        "student",
        "competition",
        "scholarship",
    ),
    ProblemCategory.FAMILY: (
        "family",
        "parent",
        "mother",
        "father",
        "child",
        "children",
        "sibling",
        "brother",
        "sister",
        "in-law",
        "domestic",
        "home conflict",
    ),
    ProblemCategory.PROPERTY: (
        "property",
        "house",
        "land",
        "real estate",
        "flat",
        "rent",
        "construction",
        "inheritance",
        "asset",
        "vehicle",
    ),
    ProblemCategory.SPIRITUAL: (
        "spiritual",
        "peace",
        "meditation",
        "purpose",
        "confusion",
        "faith",
        "karma",
        "moksha",
        "fear",
        "stress",
        "insomnia",
    ),
}

SEVERITY_KEYWORDS: dict[str, float] = {
    "critical": 0.95,
    "emergency": 0.95,
    "severe": 0.85,
    "urgent": 0.8,
    "crisis": 0.85,
    "bankruptcy": 0.9,
    "divorce": 0.85,
    "separation": 0.75,
    "loss": 0.7,
    "failed": 0.65,
    "stuck": 0.55,
    "delay": 0.5,
    "conflict": 0.6,
    "dispute": 0.6,
    "court": 0.7,
    "depression": 0.75,
    "chronic": 0.7,
    "unknown": 0.35,
    "unsure": 0.3,
    "maybe": 0.25,
    "slight": 0.2,
    "minor": 0.15,
}

NEGATION_WORDS: frozenset[str] = frozenset(
    {"no", "not", "never", "without", "none", "hardly", "barely"}
)

UNKNOWN_PHRASES: tuple[str, ...] = (
    "unknown problem",
    "not sure",
    "don't know",
    "do not know",
    "general problem",
    "many problems",
    "everything is wrong",
    "life problem",
    "no idea",
    "unclear",
)
