"""KP astrology remedy knowledge base."""

from __future__ import annotations

from remedy_engine.models.remedy import RemedyRecord

KP_REMEDIES: tuple[RemedyRecord, ...] = (
    RemedyRecord(
        remedy_id="kp_saturn_significator_support",
        remedy_name="Support Saturn Significator Remedy",
        remedy_type="behavioral",
        astrology_system="kp",
        planet="Saturn",
        house=10,
        severity="moderate",
        category="career_authority",
        description="Perform disciplined service aligned with the 10th house significator chain.",
        expected_effect="Support event fructification when Saturn is a primary significator.",
        confidence_score=0.65,
        priority=3,
    ),
    RemedyRecord(
        remedy_id="kp_venus_star_lord_harmony",
        remedy_name="Venus Star Lord Harmony Practice",
        remedy_type="behavioral",
        astrology_system="kp",
        planet="Venus",
        house=7,
        severity="moderate",
        category="marriage",
        description="Engage Venus-ruled star lord activities on Fridays for 7th house events.",
        expected_effect="Align timing support for marriage significator chains.",
        confidence_score=0.64,
        priority=3,
    ),
    RemedyRecord(
        remedy_id="kp_mercury_sub_lord_clarity",
        remedy_name="Mercury Sub Lord Clarity Routine",
        remedy_type="behavioral",
        astrology_system="kp",
        planet="Mercury",
        house=6,
        severity="moderate",
        category="legal_disputes",
        description="Maintain written records and communication discipline on Wednesdays.",
        expected_effect="Support Mercury sub lord clarity in dispute-related event analysis.",
        confidence_score=0.63,
        priority=4,
    ),
    RemedyRecord(
        remedy_id="kp_jupiter_cusp_fortification",
        remedy_name="Jupiter Cusp Fortification",
        remedy_type="ritual",
        astrology_system="kp",
        planet="Jupiter",
        house=9,
        severity="low",
        category="dharma_guidance",
        description="Offer yellow items when Jupiter appears in the 9th cusp significator set.",
        expected_effect="Reinforce benefic support in cusp-based event analysis.",
        confidence_score=0.62,
        priority=4,
    ),
    RemedyRecord(
        remedy_id="kp_rahu_node_neutralization",
        remedy_name="Rahu Node Neutralization Practice",
        remedy_type="behavioral",
        astrology_system="kp",
        planet="Rahu",
        house=12,
        severity="high",
        category="expenses_loss",
        description="Avoid speculative decisions during Rahu-dominated sub lord periods.",
        expected_effect="Reduce adverse fructification in Rahu-linked event chains.",
        confidence_score=0.61,
        priority=2,
    ),
)
