"""Lal Kitab remedy knowledge base."""

from __future__ import annotations

from remedy_engine.models.remedy import RemedyRecord

LAL_KITAB_REMEDIES: tuple[RemedyRecord, ...] = (
    RemedyRecord(
        remedy_id="lk_saturn_iron_avoid",
        remedy_name="Avoid Iron Donation When Saturn Afflicted",
        remedy_type="behavioral",
        astrology_system="lal_kitab",
        planet="Saturn",
        house=7,
        severity="high",
        category="marriage",
        description="Do not donate iron or black metal when Saturn afflicts the 7th house.",
        expected_effect="Prevent aggravation of Saturn marriage restrictions in Lal Kitab logic.",
        confidence_score=0.7,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="lk_mars_sweet_distribution",
        remedy_name="Distribute Sweets for Mars",
        remedy_type="donation",
        astrology_system="lal_kitab",
        planet="Mars",
        house=8,
        severity="high",
        category="health_obstacles",
        description="Distribute jaggery or sweets to workers on Tuesdays when Mars occupies dusthana.",
        expected_effect="Reduce Mars-linked accident and debt pressure per Lal Kitab principles.",
        confidence_score=0.68,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="lk_rahu_mustard_lamp",
        remedy_name="Mustard Oil Lamp for Rahu",
        remedy_type="ritual",
        astrology_system="lal_kitab",
        planet="Rahu",
        house=12,
        severity="moderate",
        category="expenses_loss",
        description="Keep a mustard oil lamp lit near the entrance on Saturdays.",
        expected_effect="Contain Rahu-related hidden losses and expenditure drain.",
        confidence_score=0.69,
        priority=3,
    ),
    RemedyRecord(
        remedy_id="lk_venus_white_flowers",
        remedy_name="White Flowers for Venus",
        remedy_type="ritual",
        astrology_system="lal_kitab",
        planet="Venus",
        house=2,
        severity="moderate",
        category="finance",
        description="Offer white flowers in flowing water on Fridays.",
        expected_effect="Support family wealth and speech-related Venus significations.",
        confidence_score=0.67,
        priority=3,
    ),
    RemedyRecord(
        remedy_id="lk_jupiter_yellow_donation",
        remedy_name="Yellow Donation for Jupiter",
        remedy_type="donation",
        astrology_system="lal_kitab",
        planet="Jupiter",
        house=9,
        severity="moderate",
        category="dharma_guidance",
        description="Donate yellow cloth or turmeric to priests on Thursdays.",
        expected_effect="Strengthen Jupiter dharma and guidance channels.",
        confidence_score=0.71,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="lk_moon_silver_keep",
        remedy_name="Keep Silver for Moon",
        remedy_type="behavioral",
        astrology_system="lal_kitab",
        planet="Moon",
        house=4,
        severity="moderate",
        category="mental_peace",
        description="Keep silver with mother or in the kitchen area on Mondays.",
        expected_effect="Stabilize Moon-linked domestic and emotional disturbances.",
        confidence_score=0.66,
        priority=3,
    ),
)
