"""Vedic remedy knowledge base."""

from __future__ import annotations

from remedy_engine.models.remedy import RemedyRecord

VEDIC_REMEDIES: tuple[RemedyRecord, ...] = (
    RemedyRecord(
        remedy_id="vedic_saturn_shani_mantra",
        remedy_name="Shani Mantra Japa",
        remedy_type="mantra",
        astrology_system="vedic",
        planet="Saturn",
        house=None,
        severity="moderate",
        category="karma_obstacles",
        description="Recite Shani beeja mantra on Saturdays during Shani hora.",
        expected_effect="Reduce Saturn-related delays and karmic pressure.",
        confidence_score=0.78,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="vedic_saturn_donation",
        remedy_name="Saturday Charity for Saturn",
        remedy_type="donation",
        astrology_system="vedic",
        planet="Saturn",
        house=8,
        severity="high",
        category="health_obstacles",
        description="Donate black sesame, iron items, or serve elderly on Saturdays.",
        expected_effect="Mitigate Saturn dusthana pressure and chronic obstacles.",
        confidence_score=0.74,
        priority=3,
    ),
    RemedyRecord(
        remedy_id="vedic_mars_hanuman_worship",
        remedy_name="Hanuman Worship for Mars",
        remedy_type="ritual",
        astrology_system="vedic",
        planet="Mars",
        house=7,
        severity="high",
        category="marriage",
        description="Offer red flowers and recite Hanuman Chalisa on Tuesdays.",
        expected_effect="Balance Mars aggression affecting marriage and partnerships.",
        confidence_score=0.8,
        priority=1,
    ),
    RemedyRecord(
        remedy_id="vedic_venus_white_donation",
        remedy_name="Friday Venus Charity",
        remedy_type="donation",
        astrology_system="vedic",
        planet="Venus",
        house=7,
        severity="moderate",
        category="marriage",
        description="Donate white items, sweets, or support women's welfare on Fridays.",
        expected_effect="Strengthen Venus significations for relationship harmony.",
        confidence_score=0.76,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="vedic_rahu_durga_sadhana",
        remedy_name="Durga Sadhana for Rahu",
        remedy_type="ritual",
        astrology_system="vedic",
        planet="Rahu",
        house=None,
        severity="high",
        category="confusion_obstacles",
        description="Light mustard oil lamp and chant Durga mantra on Saturdays.",
        expected_effect="Stabilize Rahu-driven confusion and sudden disruptions.",
        confidence_score=0.72,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="vedic_jupiter_guru_seva",
        remedy_name="Guru Seva for Jupiter",
        remedy_type="behavioral",
        astrology_system="vedic",
        planet="Jupiter",
        house=9,
        severity="moderate",
        category="wisdom_finance",
        description="Support teachers, scholars, or charitable education initiatives on Thursdays.",
        expected_effect="Improve Jupiter wisdom, guidance, and dharmic support.",
        confidence_score=0.77,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="vedic_moon_chandra_mantra",
        remedy_name="Chandra Mantra for Moon",
        remedy_type="mantra",
        astrology_system="vedic",
        planet="Moon",
        house=4,
        severity="moderate",
        category="mental_peace",
        description="Chant Chandra beeja mantra on Mondays during evening hours.",
        expected_effect="Calm emotional instability and strengthen mental peace.",
        confidence_score=0.75,
        priority=2,
    ),
    RemedyRecord(
        remedy_id="vedic_sun_surya_arghya",
        remedy_name="Surya Arghya",
        remedy_type="ritual",
        astrology_system="vedic",
        planet="Sun",
        house=10,
        severity="moderate",
        category="career_authority",
        description="Offer water to the rising Sun with Surya mantra at sunrise.",
        expected_effect="Support authority, vitality, and career visibility.",
        confidence_score=0.73,
        priority=3,
    ),
)
